use clap::{Parser, ValueEnum};


#[derive(Debug, Parser)]
#[clap(name="pg-loggrep", version)]
struct Arguments {
    /// number of minutes to build the average graphs of queries and connections. Default 5 minutes.
    #[clap(short, long)]
    average_minutes: Option<u32>,

    ///number of minutes to build the histogram graphs of queries. Default 60 minutes.
    #[clap(short = 'A', long)]
    histo_average: Option<u32>,

    /// start date/time for the data to be parsed in log (either a timestamp or a time)
    #[clap(short, long, value_name = "begin")]
    begin: Option<String>,

    /// only report on entries for the given client host
    #[clap(short = 'c', long, value_name = "dbclient")]
    dbclient: Option<String>,

    /// remove comments like /* ... */ from queries. Default is to keep them.
    #[clap(short = 'C', long, value_name = "nocomment")]
    nocomment: bool,

    /// only report on entries for the given database name
    #[clap(short, long, value_name = "dbname")]
    dbname: Option<String>,

    /// client ip addresses are replaced by their DNS name.
    /// Be warned that this can really slow down pgBadger.
    #[clap(short = 'D', long, value_name = "dns-resolve", action)]
    dns_resolve: bool,

    /// end date/time for the data to be parsed in log (either a timestamp or a time)
    #[clap(short, long, value_name = "end")]
    end: Option<String>,

    /// explode the main report by generating one report
    /// per database. Global information not related to a
    /// database are added to the postgres database report.
    #[clap(short = 'E', long, value_name = "explode")]
    explode: bool,

    /// Use this option when pgBadger is not able to detect the log format
    #[clap(short, long)]
    #[arg(value_enum)]
    format: Option<Format>,

    /// disable graphs on HTML output. Enabled by default.
    #[clap(short = 'G', long, value_name = "nograph")]
    nograph: bool,

    /// only report on entries for the given application name
    /// (PostgreSQL 9.0+ only)
    #[clap(short = 'N', long, value_name = "appname")]
    appname: Option<String>,

    /// path to directory where HTML report must be written in incremental mode, binary files stay on directory defined with -O, --outdir option.
    #[clap(short = 'H', long, value_name = "html-outdir")]
    html_outdir: Option<String>,

    /// programname used as syslog ident.
    #[clap(short = 'i', long, value_name = "ident", default_value = "postgres")]
    ident: Option<String>,

    /// use incremental mode, reports will be generated by days in a separate directory, --outdir must be set.
    #[clap(short = 'I', long, value_name = "incremental")]
    incremental: bool,

    /// number of jobs to run at same time. Run as single by default or when working with csvlog.
    #[clap(short = 'j', long, value_name = "jobs")]
    jobs: Option<u32>,

    /// number of log file to parse in parallel. Process one file at a time by default or when csvlog is used.
    #[clap(short = 'J', long, value_name = "Jobs")]
    parallel_parse: Option<u32>,

    /// allow incremental log parsing by registering the last datetime and line parsed. Useful if you want to watch errors since last run or if you want one report per day with a log rotated each week.
    #[clap(short = 'l', long, value_name = "last-parsed")]
    last_parsed: Option<String>,

    /// file containing a list of log file to parse.
    #[clap(short = 'L', long, value_name = "logfile-list")]
    logfile_list: Option<String>,

    /// maximum length of a query, it will be restricted to the given size. Default truncate size is 100000.
    #[clap(short = 'm', long, value_name = "maxlength")]
    maxlength: Option<u32>,

    /// do not collect multiline statement to avoid garbage especially on errors that generate a huge report.
    #[clap(short = 'M', long, value_name = "no-multiline")]
    no_multiline: bool,

    /// disable SQL code highlighting.
    #[clap(short = 'n', long, value_name = "nohighlight")]
    nohighlight: bool,

    /// define the filename for the output. Default depends on the output format: out.html, out.txt, out.bin, out.json or out.tsung. This option can be used multiple time to output several format. To use json output the Perl module JSON::XS must be installed, To dump output to stdout use - as filename.
    #[clap(short = 'o', long, value_name = "outfile")]
    outfile: Option<String>,

    /// directory where out file must be saved.
    #[clap(short = 'O', long, value_name = "outdir")]
    outdir: Option<String>,

    /// the value of your custom log_line_prefix as defined in your postgresql.conf. Only use it if you aren't using one of the standard prefixes specified in the pgBadger documentation, such as if your prefix includes additional variables like client ip or application name. See examples below.
    #[clap(short = 'p', long, value_name = "prefix")]
    prefix: Option<String>,

    /// disable SQL queries prettify formatter.
    #[clap(short = 'P', long, value_name = "no-prettify")]
    no_prettify: bool,

    /// don't print anything to stdout, not even a progress bar.
    #[clap(short = 'q', long, value_name = "quiet")]
    quiet: bool,

    /// add numbering of queries to the output when using options --dump-all-queries or --normalized-only.
    #[clap(short = 'Q', long, value_name = "query-numbering")]
    query_numbering: bool,

    /// set the host where to execute the cat command on remote logfile to parse locally the file.
    #[clap(short = 'r', long, value_name = "remote-host")]
    remote_host: Option<String>,

    /// number of weeks to keep in incremental mode. Default to 0, disabled. Used to set the number of weeks to keep in output directory. Older weeks and days directory are automatically removed.
    #[clap(short = 'R', long, value_name = "retention")]
    retention: Option<u32>,

    /// number of query samples to store.
    #[clap(short = 's', long, value_name = "sample", default_value = "3")]
    sample: Option<u32>,

    /// only report SELECT queries.
    #[clap(short = 'S', long, value_name = "select-only")]
    select_only: bool,

    /// change title of the HTML page report.
    #[clap(short = 'T', long, value_name = "title")]
    title: Option<String>,

    /// only report on entries for the given user.
    #[clap(short = 'u', long, value_name = "dbuser")]
    dbuser: Option<String>,

    /// exclude entries for the specified user from report. Can be used multiple time.
    #[clap(short = 'U', long, value_name = "exclude-user")]
    exclude_user: Option<String>,

    /// enable verbose or debug mode. Disabled by default.
    #[clap(short = 'v', long, value_name = "verbose", default_value = "false")]
    verbose: bool,

    /// only report errors just like logwatch could do.
    #[clap(short = 'w', long, value_name = "watch-mode")]
    watch_mode: bool,

    /// encode html output of queries into UTF8 to avoid Perl message "Wide character in print".
    #[clap(short = 'W', long, value_name = "wide-char")]
    wide_char: bool,

    /// output format. Values: text, html, bin, json or tsung.
    #[clap(short = 'x', long, value_name = "extension", default_value = "html")]
    extension: Option<String>,

    /// in incremental mode allow pgBadger to write CSS and JS files in the output directory as separate files.
    #[clap(short = 'X', long, value_name = "extra-files")]
    extra_files: bool,

    /// set the full path to the zcat program. Use it if zcat or bzcat or unzip is not in your path.
    #[clap(short = 'z', long, value_name = "zcat")]
    zcat: Option<String>,

    /// Set the number of hours from GMT of the timezone. Use this to adjust date/time in JavaScript graphs.
    #[clap(short = 'Z', long, value_name = "timezone")]
    timezone: Option<String>,

    /// pie data lower than num% will show a sum instead.
    #[clap(long, value_name = "pie-limit")]
    pie_limit: Option<u32>,

    /// any query matching the given regex will be excluded from the report. For example: "^(VACUUM|COMMIT)"
    #[clap(long, value_name = "exclude-query")]
    exclude_query: Option<String>,

    /// path of the file which contains all the regex to use to exclude queries from the report. One regex per line.
    #[clap(long, value_name = "exclude-file")]
    exclude_file: Option<String>,

    /// any query that does not match the given regex will be excluded from the report. You can use this option multiple times. For example: "(tbl1|tbl2)".
    #[clap(long, value_name = "include-query")]
    include_query: Option<String>,

    /// path of the file which contains all the regex of the queries to include from the report. One regex per line.
    #[clap(long, value_name = "include-file")]
    include_file: Option<String>,

    /// do not generate error report.
    #[clap(long, value_name = "disable-error")]
    disable_error: bool,

    /// do not generate hourly report.
    #[clap(long, value_name = "disable-hourly")]
    disable_hourly: bool,

    /// do not generate report of queries by type, database or user.
    #[clap(long, value_name = "disable-type")]
    disable_type: bool,

    /// do not generate query reports (slowest, most frequent, queries by users, by database, ...).
    #[clap(long, value_name = "disable-query")]
    disable_query: bool,

    /// do not generate session report.
    #[clap(long, value_name = "disable-session")]
    disable_session: bool,

    /// do not generate connection report.
    #[clap(long, value_name = "disable-connection")]
    disable_connection: bool,

    /// do not generate lock report.
    #[clap(long, value_name = "disable-lock")]
    disable_lock: bool,

    /// do not generate temporary report.
    #[clap(long, value_name = "disable-temporary")]
    disable_temporary: bool,

    /// do not generate checkpoint/restartpoint report.
    #[clap(long, value_name = "disable-checkpoint")]
    disable_checkpoint: bool,

    /// do not generate autovacuum report.
    #[clap(long, value_name = "disable-autovacuum")]
    disable_autovacuum: bool,

    /// used to set the HTML charset to be used.
    #[clap(long, value_name = "charset", default_value = "utf-8")]
    charset: Option<String>,

    /// used to set the CSV field separator
    #[clap(long, value_name = "csv-separator", default_value = ",")]
    csv_separator: Option<String>,

    /// any timestamp matching the given regex will be excluded from the report. Example: "2013-04-12 .*"
    #[clap(long, value_name = "exclude-time")]
    exclude_time: Option<String>,

    /// only timestamps matching the given regex will be included in the report. Example: "2013-04-12 .*"
    #[clap(long, value_name = "include-time")]
    include_time: Option<String>,

    /// exclude entries for the specified database from report. Example: "pg_dump". Can be used multiple time.
    #[clap(long, value_name = "exclude-db")]
    exclude_db: Option<String>,

    /// exclude entries for the specified application name from report.  Example: "pg_dump".  Can be used multiple time.
    #[clap(long, value_name = "exclude-appname")]
    exclude_appname: Option<String>,

    /// pgBadger will start to exclude any log entry that will match the given regex. Can be used multiple time.
    #[clap(long, value_name = "exclude-line")]
    exclude_line: Option<String>,

    /// exclude log entries for the specified client ip. Can be used multiple time.
    #[clap(long, value_name = "exclude-client")]
    exclude_client: Option<String>,

    /// obscure all literals in queries, useful to hide confidential data.
    #[clap(long, value_name = "anonymize")]
    anonymize: bool,

    /// prevent pgBadger to create reports in incremental mode.
    #[clap(long, value_name = "noreport")]
    noreport: bool,

    /// force pgBadger to associate log entries generated by both log_duration = on and log_statement = 'all'
    #[clap(long, value_name = "log-duration")]
    log_duration: bool,

    /// used to add a md5 sum under each query report.
    #[clap(long, value_name = "enable-checksum")]
    enable_checksum: bool,

    /// command to use to replace PostgreSQL logfile by a call to journalctl. Basically it might be: journalctl -u postgresql-9.5
    #[clap(long, value_name = "journalctl")]
    journalctl: Option<String>,

    /// set the path where the pid file must be stored. Default /tmp
    #[clap(long, value_name = "pid-dir", default_value = "/tmp")]
    pid_dir: Option<String>,

    /// set the name of the pid file to manage concurrent execution of pgBadger. Default: pgbadger.pid
    #[clap(long, value_name = "pid-file", default_value = "pgbadger.pid")]
    pid_file: Option<String>,

    /// used to rebuild all html reports in incremental output directories where there's binary data files.
    #[clap(long, value_name = "rebuild")]
    rebuild: bool,

    /// only show PgBouncer related menu in the header.
    #[clap(long, value_name = "pgbouncer-only")]
    pgbouncer_only: bool,

    /// in incremental mode, calendar's weeks start on a sunday. Use this option to start on a monday.
    #[clap(long, value_name = "start-monday")]
    start_monday: bool,

    /// in incremental mode, calendar's weeks start on a monday and respect the ISO 8601 week number, range 01 to 53, where week 1 is the first week that has at least 4 days in the new year.
    #[clap(long, value_name = "iso-week-number")]
    iso_week_number: bool,

    /// only dump all normalized query to out.txt
    #[clap(long, value_name = "normalized-only")]
    normalized_only: bool,

    /// do not process lines generated by auto_explain.
    #[clap(long, value_name = "noexplain")]
    noexplain: bool,

    /// command to execute to retrieve log entries on stdin. pgBadger will open a pipe to the command and parse log entries generated by the command.
    #[clap(long, value_name = "command")]
    command: Option<String>,

    /// disable changing process title to help identify pgbadger process, some system do not support it.
    #[clap(long, value_name = "no-process-info")]
    no_process_info: bool,

    /// dump all queries found in the log file replacing bind parameters are included in the queries at their respective placeholders position.
    #[clap(long, value_name = "dump-all-queries")]
    dump_all_queries: bool,

    /// do not remove comments from normalized queries. It can be useful if you want to distinguish between same normalized queries.
    #[clap(long, value_name = "keep-comments")]
    keep_comments: bool,

    /// disable progressbar.
    #[clap(long, value_name = "no-progressbar")]
    no_progressbar: bool,
}

#[derive(Debug, ValueEnum, Clone, Copy, Default)]
enum Format {
    #[default]
    Syslog,
    Syslog2,
    Stderr,
    Jsonlog,
    Cvs,
    Pgbouncer,
    Logplex,
    Rds,
    Redshift,
}

fn main() {
    let args = Arguments::parse();
    println!("The format is: {:?}", args.format.unwrap_or_default());
}